server:
  port: 8081
  shutdown: immediate
spring:
  lifecycle:
    timeout-per-shutdown-phase: 1s
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: Daisilong123
      database: 0
ibkr:
  base-url: ${IBKR_BASE_URL:http://8.211.150.14:8082}
  api-key: ${IBKR_API_KEY:}
