server:
  port: 8081
  shutdown: immediate
spring:
  lifecycle:
    timeout-per-shutdown-phase: 1s
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qtt_app?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Daisilong123.
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: Daisilong123
      database: 0
ibkr:
  base-url: ${IBKR_BASE_URL:http://8.211.150.14:8082}
  api-key: ecaff9bade376ad512d8ba74880fe64ad03bfe3478ad12801ec0d346dffc02bf
