server:
  port: 8081
  shutdown: immediate
spring:
  lifecycle:
    timeout-per-shutdown-phase: 1s
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: Daisilong123
      database: 0
